version: '2.1'
services:
  database:
    image: postgres:10.5
    container_name: postgres_docker
    volumes:
      - ./setup/postgres_docker:/docker-entrypoint-initdb.d/
    env_file:
      .env
  vault:
    build: .
    container_name: vault_plugin
    depends_on:
      - database
    ports:
      - 8200:8200
    links:
      - database
    cap_add:
      - IPC_LOCK
    env_file:
      .env
    volumes:
      - ./setup/config.hcl:/vault/config/config.hcl
    command: make run
